### ISSUE TITLE
[Release Changelogs] v0.1.1

### ISSUE THREAD

**Issue by juicity-svc-infra** [juicity/juicity-1#1]
## Context

🚀 @daebot proposed the following changelogs for release v0.1.1 generated in [workflow run](https://github.com/juicity/juicity/actions/runs/5706551791).

### Features
- feat(server): support fwmark in [#18](https://github.com/juicity/juicity/pull/18) by (mzz2017)
- feat: support send_through in [#17](https://github.com/juicity/juicity/pull/17) by (mzz2017)

### Bug Fixes
- hotfix/ci(build): fix secret inputs missing issue in [#33](https://github.com/juicity/juicity/pull/33) by (@yqlbu)
- fix: should support hex fwmark in [#20](https://github.com/juicity/juicity/pull/20) by (mzz2017)
- hotfix: fix server instantiation in [#19](https://github.com/juicity/juicity/pull/19) by (@yqlbu)

### Others
- ci: add generate-changelogs workflow in [#37](https://github.com/juicity/juicity/pull/37) by (@yqlbu)
- ci(build,daily-build): demise post-actions stage in [#35](https://github.com/juicity/juicity/pull/35) by (@yqlbu)
- ci(build,pr-build,daily-build): enable check_run stages in [#[32](https://github.com/juicity/juicity/actions/runs/5706551791/job/15462354120#step:4:33)](https://github.com/juicity/juicity/pull/32) by (@yqlbu)
- chore: add example-{client,server}.json in [#29](https://github.com/juicity/juicity/pull/29) by (@mzz2017)
- chore/optimize(log): change log format to datetime in [#26](https://github.com/juicity/juicity/pull/26) by (@mzz2017)
- docs: refine README in [#25](https://github.com/juicity/juicity/pull/25) by (@mzz2017)
- docs(readme): add daed client as a new juicity client in [#21](https://github.com/juicity/juicity/pull/21) by (@mzz2017)
- refactor/patch: rework logger instantiation in [#16](https://github.com/juicity/juicity/pull/16) by (@yqlbu)
- ci/feature: add release builds in [#15](https://github.com/juicity/juicity/pull/15) by (@yqlbu)

**Full Changelog**: https://github.com/juicity/juicity/compare/v0.1.0...v0.1.1

**Comment by yqlbu** [comment]
@juicity-bot proceed to release-v0.1.1

**Comment by yqlbu** [comment]
@juicity-bot proceed to release-v0.1.1

**Comment by yqlbu** [comment]
@juicity-bot proceed to release-v0.1.1
